language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
    - secure: gvvc6dDiOEZAUqD/hkkj7mVQCCVql88eENwcUmCA2Pvw9D1YlY0YcPXQCMcNTfC2eZB8okTcPjdnsaJUlcQv8oigBsgjeUsEkSlcVjJeM9SxEttCOlCYXVtcH3pG8Qrh6WKhGsm2v+SYlTjAhSKO1c3iONBJczMRMkXU8PYeFDAt4X+2eBaMdOgd7dt9zqQzoEfWDR6g7OC5uzBJOzGrkmnBqSPjKlO9ni4hC/7I7T328jYUULhqa8G5Fsvyxxd0qActGPbfPeFMjuFDce6h9W9K+RcjcI3Srxao71iyCkjlmE3/ATtHHimcscqvMgNyqQM9Le2Xi2vqYcvl9F1zr0d+Gllpb8TmTRR2IrohxUB1Kb+5kmMUrqLACRf024PUsOdgIGk9XZxd2UF4wcPcfuy90j0PXVHD8uORufQhFXcMa0DmYKrC67EMo/UyJ7y3tXv+Eaf3E/AGEmYDX9meMudlep7rejVOWgmqPp/jxLtaVXrqthxvJCgkQvDSduAEGSVqwxAa5N0qIBx8NS/E5rBS3yRrOv5+OfFe2GjWbHr3q/uYRzta2/Gxzw1izV7iJSFfyvt3mrW0sHu3cIX2aGHzbZBYquM3deFQaPa8inhECr38esxI93+eBf3f6CiQue3m1SiJpavt9P4bTDW1dm+KNIWdy6k0QE4aE1XruW4=
    - secure: pVpkSz4ppVZJHfZLzXI4TVFfa3+2ZYqPyWua9Y3d3tFhGlmQ3uP8n0IDOSXMOUsagtHOcp2QbEjgcfXx9/4fG07fzWS5SglEhus3fKYVl552PCYvXl3wO/bPvxd4VdUGk0FeuQUBw0Ehnt3t2xuVlQR+43sdBOiLUHJ2w4Ls5Y5aEBjhCN4oIjBAswVsk3jBGZCdEWfwMOPCzJAG2tKYQ2BHvUh91b1hR3RaD6WYGTWUTltL398NInMgyPajC/LoQnsC+H+I9K9HHckDnRdQlqW0kEO5PMdxUh4bARbmnVkdokpm1Gw/aO07nPU4Ck5+WZ+U0BI2Vq1kWzxM5XZaJDnJ2ybIBLzGle8+HrmRjM0VIhXwLLeiqIqwS6yyhygR0mT/0jur24dvKv2wyJUGrgPsr/3CZckpokc5zkCe3rSgTglPJbZMqiFOgPG49v79+dZm3wOOyHjfbYaKMKKIC7tVKC5ppKefm0vHogwjvZOs13HDr/cCgC5XqnZTaew4ixwxIrPh25SlhxeSfTK0mC2wKaTJkrulgyeuU5N0v92dvMpXbnvZtnAGEtkPvagQRJgZ808fs7qIfyx6HcwFoqdpMkdayonUHJqKdM3JIQBv2wPkUtdzOSXZZw9etifcxE8bEWcKRheVmFJgGApNph30ZefdNwRjYDmlFzSChmA=
  email: false
addons:
  sauce_connect: true
before_script: npm install -g karma-cli
